version: '3.6'
services:
  liquid:
    image: asoltys/liquid:latest
    container_name: liquid
    ports:
      - ${LIQUID_NODE_PORT}:18884
      - ${LIQUID_PEER_PORT}:18886
      - ${LIQUID_BLOCK_PORT}:18602
      - ${LIQUID_TX_PORT}:18603
    volumes:
      - ./data/:/config
    restart: unless-stopped
  electrs-liquid:
    image: vulpemventures/electrs-liquid:latest
    container_name: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:3002
      - --electrum-rpc-addr
      - 0.0.0.0:60401
      - --cors
      - "*"
    depends_on:
      - liquid
    ports:
      - ${LIQUID_ELECTRS_RPC_PORT}:60401
      - ${LIQUID_ELECTRS_PORT}:3002
    volumes:
      - ./data/:/config
    restart: unless-stopped
